package com.example.dynamojavatest.models;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import org.springframework.data.annotation.Id;
import org.springframework.data.redis.core.RedisHash;

@DynamoDBTable(tableName = "Users")
@RedisHash("Users")
public class UserData {



    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @Id
    private String Id;

    private String name;
    private String email;

    public UserData() {
    }

    public UserData(String Id, String name, String email) {
        this.Id = Id;
        this.name = name;
        this.email = email;
    }

    /**
     * @return String return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return String return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return String return the Id
     */
    @DynamoDBHashKey(attributeName = "Id")
    public String getId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(String Id) {
        this.Id = Id;
    }

}
